### PR TITLE
Update to the same stage as the cpp plugin

### PR DESCRIPTION
**Pull request by Asd-g**
Along with the added features it should compile under Linux but currently it's missing such building option (meson/makefile).

### CODE REVIEW

**Comment by qyot27** [comment]
Two or three points:
* The C interface was not actually able to work with frame properties correctly with v8, until it was fixed in https://github.com/AviSynth/AviSynthPlus/commit/0a6d30a10b31902ceedd1d589322cf03dbe92f44 (it was also what lead to the introduction of the INTERFACE_BUGFIX version in https://github.com/AviSynth/AviSynthPlus/commit/b73f6e8fd7a245998b76b310128822de70b43765, so the fixes for the C interface are only guaranteed to be present with v8.1...which is close enough to v9 to probably just make it easier to check for v9).  It was something that was addressed in v3.7.1.  Unless I was misunderstanding something about how that fix applies to updating (specifically, C) plugins vs clients.

* Linux-wise, [a commit to do that is present on the `linux` branch of the repo here](https://github.com/qyot27/ffms2_cplugin/commit/f1b10508f015c0b52d19c2ec583ceaff575492e1).  The problem, like I mentioned in the commit message, was that I had to disable the plugin's dynamic loader on Linux to do it (so the code is essentially the same as the commit here, except that there's no OS branching to retain both behaviors).

  For Windows, the fact that the C plugin uses that dynamic loading system is something of a novelty (I don't know any other plugin that works that way), but also makes it far easier to maintain since it doesn't need to link to AviSynth.lib after messing around with gendef or whatnot (or, considering that the C plugin was intended as a way of building with GCC, libavisynth.a - and I have no idea how an MSVC-built AviSynth core would react to a C plugin linked to MinGW-built libavisynth).  It's almost certain the reason it exists is to allow the plugin to be built without having to mess with manipulating MSVC-built libraries, since that part has been around way longer than even AviSynth+ has existed.

  The ideal solution really would be to find some way of making the dynamic loader mechanism work on Linux like it does on Windows, so that we don't have to branch the code.

* One lingering difference with the C++ plugin that's existed for years are the changes in https://github.com/ffms/ffms2/commit/ef3b46bc22cd6cadd7b20708322f8f4d0d876053 and https://github.com/ffms/ffms2/commit/817be40c01bb8798c3b1c334d3aa138dede31075, where the `FFmpegSource2` (and the shorter `FFMS2` alias)  wrapping function was ported to C++ and removed from FFMS2.avsi.

**Comment by Asd-g** [comment]
> For Windows, the fact that the C plugin uses that dynamic loading system is something of a novelty (I don't know any other plugin that works that way), but also makes it far easier to maintain since it doesn't need to link to AviSynth.lib after messing around with gendef or whatnot (or, considering that the C plugin was intended as a way of building with GCC, libavisynth.a - and I have no idea how an MSVC-built AviSynth core would react to a C plugin linked to MinGW-built libavisynth).  It's almost certain the reason it exists is to allow the plugin to be built without having to mess with manipulating MSVC-built libraries, since that part has been around way longer than even AviSynth+ has existed.<br>
>       The ideal solution really would be to find some way of making the dynamic loader mechanism work on Linux like it does on Windows, so that we don't have to branch the code.

For Windows (building the plugin with Mingw GCC) linking against both AviSynth.lib created by MSVC like compiler or AviSynth.dll.a created by Mingw GCC doesn't require nothing additional (at least for x64) - just linking. Both methods work fine with MSVC-built AviSynth. The  only hassle is just building AviSynth (w/ or w/o plugins). IMO it's even easier for maintaining because one shouldn't manually add any new API function to avs_lib.h, avs_lib.c.

For Linux one usually already have built AviSynth lib in order to use AviSynth in first place. I can't see any benefit of dynamically loading for this case.

**Comment by Asd-g** [comment]
Interface v8.1 is now required for the frame properties.

Added FFmpegSource2/FFMS2 and the other functions.

For Windows - the plugin now can be compiled with either MSVC (including clang-cl) or Mingw GCC.

Edit: Yes, dynamic load is required for Windows due compatibility with older AviSynth+/AviSynth.

**Comment by qyot27** [comment]
Was closing this an accident?

I was trying to test it on Linux last night (so, before the latest couple of changes), and while it would indeed build, it resulted in a segfault when I tried to run a script.  Moreso, when I attempted to cross compile for Windows, meson would just hang during `meson setup`, even though native builds were fine (and I can [easily cross-compile many other things with meson](https://github.com/qyot27/mpv/blob/extra-new/DOCS/crosscompile-mingw-tedious.txt)*, that wasn't the issue).

*I still have yet to update the instructions for mpv itself now that it's fully moved to meson and deleted waf, though.

**Comment by Asd-g** [comment]
I closed this because I have to reimplement the dynamic load at least for Windows. I probably will do it like the x264 dynamic load. I probably will rebase the repo from [b6efe80](https://github.com/qyot27/ffms2_cplugin/pull/4/commits/b6efe800a4cfd7e059a6fe3539be55651faa0fcf) in order to keep the history more clean.

For example without the dynamic load and with the current code (with audio channel mask) the required AviSynth+ version for both building and running the plugin (on the client side) is r4001. Building against older version (<r4001) will result in unresolved symbols. Running the plugin with older version (<r4001) will result to crash. And removing the channel mask code will require AviSynth+ 3.6 because of the frame properties.

I don't tested MinGW building under Linux, only the MSYS2 one. I don't tested meson much, mainly using configure/GNUMakefile and Visual Studio 2022 for the MSVC build.

**Pull request closed without merging**
